### ISSUE TITLE
Bootstrap 3&4 overwrites table default style

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5-table#154]
Working on issues related to the bootstrap integration I've found changed `.table` behaviour:

```html
<figure class="table ck-widget ck-widget_selectable">
```

![screenshot 2018-12-07 at 11 25 00](https://user-images.githubusercontent.com/10219857/49642742-2c0adf00-fa14-11e8-9f90-66fef375c3ba.png)

### Bootstrap 4:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tables.scss#L6

```css
.table {
  width: 100%;
  margin-bottom: $spacer;
  background-color: $table-bg; // Reset for nesting within parents with `background-color`.
}
```

### Bootstrap 3 
https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css

```css
.table {
  width: 100%;
  margin-bottom: 20px;
}
```

cc @oleq

**Comment by oleq** [comment]
If we considered a fix, would that be some code
* in table feature styles,
* or in table content styles,
* or in docs
?

**Comment by dkonopka** [comment]
I was thinking about fixing it inside [table content styles](https://github.com/ckeditor/ckeditor5-table/blob/master/theme/table.css). 

There is also thing to consider, I mean the way to override bootstrap styles:
```css
.ck-content .table {
  width: auto;
  width: unset;
  width: inherit;
}
```
