### ISSUE TITLE
The nested editable selection indicator is broken

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#69]
When there are colspans/rowspans in cells the border-based selection is messed up:

![selection_041](https://user-images.githubusercontent.com/247363/41599703-43a2480e-73d4-11e8-835a-bfda23e8d6ae.png)

I've found that the `box-shadow: inset` plays well:

![selection_042](https://user-images.githubusercontent.com/247363/41599808-85ea94aa-73d4-11e8-827c-bc59b81b6799.png)

I've used this:
```css
.ck-widget.table {
	& td,
	& th {
		&.ck-editor__nested-editable.ck-editor__nested-editable_focused {
			border-style: none;
			box-shadow: var(--ck-inner-shadow), 0 0, inset 0px 0px 0 1px var(--ck-color-focus-border);
		}
	}
}
```

**Comment by dtwist** [comment]
To reiterate an [earlier comment](https://github.com/ckeditor/ckeditor5-table/pull/23#issuecomment-393329822) on this:

Use outline instead of border:
https://codepen.io/david-twist/pen/NMQOwO?editors=1000

```css
.highlight {
  outline: 3px solid rgb(71, 164, 245);
  outline-offset: -1px; /* progressive enhancement - no IE support */
  box-shadow: inset 2px 2px 4px rgba(0, 0, 0, .2);
}
```

**Comment by jodator** [comment]
So here is a comparison of a highlighting:

1. Current:

Chrome | Firefox | Edge
-----------|-----------|-------
![selection_076](https://user-images.githubusercontent.com/247363/41716536-0be815a4-7557-11e8-83b8-347c530f4d05.png) | ![selection_072](https://user-images.githubusercontent.com/247363/41716427-afd4a1ec-7556-11e8-8df8-29a3e45154cd.png) | ![selection_073](https://user-images.githubusercontent.com/247363/41716484-de7bf8a6-7556-11e8-967e-7c26335b6946.png)

2. Using `box-shadow`:

Chrome | Firefox | Edge
-----------|-----------|-------
![selection_077](https://user-images.githubusercontent.com/247363/41716539-0e93fe58-7557-11e8-9c50-da99ecb50e7b.png) | ![selection_071](https://user-images.githubusercontent.com/247363/41716436-b501140c-7556-11e8-8656-c0c6b4555783.png) | ![selection_074](https://user-images.githubusercontent.com/247363/41716479-db378ca0-7556-11e8-8c5f-aa10aac48071.png)

3. Using outline:

Chrome | Firefox | Edge
-----------|-----------|-------
![selection_078](https://user-images.githubusercontent.com/247363/41716541-127cb5f0-7557-11e8-9ed2-659d58f50289.png) | ![selection_069](https://user-images.githubusercontent.com/247363/41716441-b8dc4fec-7556-11e8-9276-de32f3bb1856.png) | ![selection_075](https://user-images.githubusercontent.com/247363/41716475-d894715c-7556-11e8-907a-262cf4b12106.png)

From the above:
1. The current solution is broken on Chrome - no go.
2. The `box-shadow` solution is slightly worse (on Edge) from others and doesn't look so nice (also the upper shadow sometimes get lost on Edge).
3. Looks nice everywhere IMHO.

I'd go with @dtwist solution:

```css
.ck-widget.table {
	& td,
	& th {
		&.ck-editor__nested-editable.ck-editor__nested-editable_focused {
			border-style: none;
			outline: 1px solid var(--ck-color-focus-border);
			outline-offset: -1px; /* progressive enhancement - no IE support */
		}
	}
}
```

@oleq & @dkonopka Let me know if you wish to change the background as well.
